//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App1_MI
{
    using System;
    using System.Collections.Generic;
    
    public partial class KLIENCI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KLIENCI()
        {
            this.WYPOZYCZENIA = new HashSet<WYPOZYCZENIA>();
        }
    
        public int IDklienta { get; set; }
        public string Nazwisko { get; set; }
        public string Imie { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string Nr_domu { get; set; }
        public string Nr_telefonu { get; set; }
        public string Firma { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WYPOZYCZENIA> WYPOZYCZENIA { get; set; }
    }
}
