//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App1_MI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRACOWNICY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRACOWNICY()
        {
            this.WYPOZYCZENIA = new HashSet<WYPOZYCZENIA>();
            this.WYPOZYCZENIA1 = new HashSet<WYPOZYCZENIA>();
        }
    
        public int IDpracownika { get; set; }
        public int IDsiedziby { get; set; }
        public byte[] Nazwisko { get; set; }
        public byte[] Imie { get; set; }
        public System.DateTime Data_zatrudnienia { get; set; }
        public string Nr_telefonu { get; set; }
    
        public virtual SIEDZIBY SIEDZIBY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WYPOZYCZENIA> WYPOZYCZENIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WYPOZYCZENIA> WYPOZYCZENIA1 { get; set; }
    }
}
