//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App1_MI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SIEDZIBY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SIEDZIBY()
        {
            this.PRACOWNICY = new HashSet<PRACOWNICY>();
            this.WYPOZYCZENIA = new HashSet<WYPOZYCZENIA>();
            this.WYPOZYCZENIA1 = new HashSet<WYPOZYCZENIA>();
        }
    
        public int IDsiedziby { get; set; }
        public string Miasto { get; set; }
        public string Ulica { get; set; }
        public string Nr_domu { get; set; }
        public string Kod_pocztowy { get; set; }
        public string Nr_telefonu { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRACOWNICY> PRACOWNICY { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WYPOZYCZENIA> WYPOZYCZENIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WYPOZYCZENIA> WYPOZYCZENIA1 { get; set; }
    }
}
