//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App1_MI
{
    using System;
    using System.Collections.Generic;
    
    public partial class WYPOZYCZENIA
    {
        public int IDwypozyczenia { get; set; }
        public int IDklienta { get; set; }
        public int IDsamochodu { get; set; }
        public int IDpracownika_wyp { get; set; }
        public int IDsiedziby_wyp { get; set; }
        public System.DateTime Data_wyp { get; set; }
        public Nullable<int> IDpracownika_odd { get; set; }
        public Nullable<int> IDsiedziby_odd { get; set; }
        public Nullable<System.DateTime> Data_odd { get; set; }
        public double Cena_jedn { get; set; }
    
        public virtual KLIENCI KLIENCI { get; set; }
        public virtual PRACOWNICY PRACOWNICY { get; set; }
        public virtual PRACOWNICY PRACOWNICY1 { get; set; }
        public virtual SAMOCHODY SAMOCHODY { get; set; }
        public virtual SIEDZIBY SIEDZIBY { get; set; }
        public virtual SIEDZIBY SIEDZIBY1 { get; set; }
    }
}
